#!/bin/bash

PORT="2220"
IP="139.59.241.127"
PNAME="dash_game"

rm -r ../node_modules
ssh -p $PORT node@$IP "rm -r ~/projects/$PNAME"
scp -r -P $PORT ../../$PNAME node@$IP:~/projects/$PNAME
ssh -p $PORT node@$IP "cd ~/projects/$PNAME; npm install"
cd ../; npm install