#!/bin/bash

PORT="2220"
IP="139.59.241.127"
PNAME=$1

rm -r ../node_modules
ssh -p $PORT node@$IP "rm -r ~/$PNAME"
scp -r -P $PORT ../../$PNAME node@$IP:~/$PNAME
ssh -p $PORT node@$IP "cd ~/$PNAME; npm install"
cd ../; npm install
